Add shop.inc ind jwp_skin
TiBarification/Jail-Warden-Pro pull request #62
Opened 2017-07-22 11:19 UTC by mrkos9i4ok

2017-07-22 11:54 UTC, TiBarification requested changes
Remove this file (shop.inc), cause it is old version of it.
Use reference to fork repository by R1KO.
I'm thinking about reconstruction builder (travis-ci),

2017-07-22 14:53 UTC, TiBarification commented
@mrkos9i4ok you need to add support if server does not have [Shop] Core plugin. I added support for Fork by @R1KO.

2017-07-22 17:26 UTC, TiBarification submitted a review, later dismissed

2017-07-22 17:26 UTC, TiBarification commented on .travis.yml
> +    - mv addons/sourcemod/scripting/include/n_arms_fix.inc jwp/addons/sourcemod/scripting/include/
Your code is not up to date. Please use latest commit for your changes.

2017-08-03 11:31 UTC, mrkos9i4ok commented
What `not travis`

2017-08-03 11:32 UTC, TiBarification commented
I help you to fix this commit.

2017-08-03 11:49 UTC, TiBarification commented
@mrkos9i4ok fixed integration with jwp_skin module.

2017-08-03 11:52 UTC, mrkos9i4ok commented
Still have to know how)))

2017-08-03 11:53 UTC, TiBarification commented
Build is failed, because your module jwp_ratio uses lib `mystocks` that isn't default and not in list of travis. Add this lib manually, or just add a simple functions that it uses.

2017-08-03 11:57 UTC, TiBarification commented
Congradulations with passed build.

2017-08-03 12:10 UTC, mrkos9i4ok commented
Now can this be closed?

2017-08-03 12:29 UTC, merged