New module:antiafk
TiBarification/Jail-Warden-Pro pull request #64
Opened 2017-08-06 10:07 UTC by mrkos9i4ok

2017-08-06 10:21 UTC, mrkos9i4ok commented
I need help to get the phrases through a translator

2017-08-06 10:42 UTC, mrkos9i4ok commented
wow xD

2017-08-06 11:58 UTC, TiBarification reviewed
Explain

2017-08-06 11:58 UTC, TiBarification commented on addons/sourcemod/scripting/jwp_antiafk.sp
> +						JWP_ActionMsgAll("{GREEN}[{RED}JWP{PURPLE}.{BLUE}AFK{GREEN}] {BLUE}%N {DEFAULT}получает  1/2 предупреждений",i);
What is this?

2017-08-06 11:58 UTC, TiBarification commented on README.md
> -[![CircleCI](https://circleci.com/gh/TiBarification/Jail-Warden-Pro/tree/dev.svg?style=svg)](https://circleci.com/gh/TiBarification/Jail-Warden-Pro/tree/dev)
Why are you deleting those rows?

2017-08-06 12:04 UTC, mrkos9i4ok commented on addons/sourcemod/scripting/jwp_antiafk.sp
> +						JWP_ActionMsgAll("{GREEN}[{RED}JWP{PURPLE}.{BLUE}AFK{GREEN}] {BLUE}%N {DEFAULT}получает  1/2 предупреждений",i);
In the first round AFK, the guard will simply be killed
In the second round, he will be killed and transferred for a team of prisoners

2017-08-06 12:05 UTC, mrkos9i4ok commented on README.md
> -[![CircleCI](https://circleci.com/gh/TiBarification/Jail-Warden-Pro/tree/dev.svg?style=svg)](https://circleci.com/gh/TiBarification/Jail-Warden-Pro/tree/dev)
I did not have a dev branch and therefore it did not work, but this does not apply to this

2017-08-06 12:13 UTC, TiBarification commented on README.md
> -[![CircleCI](https://circleci.com/gh/TiBarification/Jail-Warden-Pro/tree/dev.svg?style=svg)](https://circleci.com/gh/TiBarification/Jail-Warden-Pro/tree/dev)
CircleCI can be removed on both branches (master, dev)

2017-08-06 12:14 UTC, TiBarification commented on addons/sourcemod/scripting/jwp_antiafk.sp
> +						JWP_ActionMsgAll("{GREEN}[{RED}JWP{PURPLE}.{BLUE}AFK{GREEN}] {BLUE}%N {DEFAULT}получает  1/2 предупреждений",i);
But why there are warnings?

2017-08-06 12:30 UTC, mrkos9i4ok commented on addons/sourcemod/scripting/jwp_antiafk.sp
> +						JWP_ActionMsgAll("{GREEN}[{RED}JWP{PURPLE}.{BLUE}AFK{GREEN}] {BLUE}%N {DEFAULT}получает  1/2 предупреждений",i);
![image](https://user-images.githubusercontent.com/20227450/29003255-027be248-7abc-11e7-8c30-2979390fd000.png)
I don't understand the question!
I have everything on the server.

2017-08-06 12:34 UTC, TiBarification commented on addons/sourcemod/scripting/jwp_antiafk.sp
> +						JWP_ActionMsgAll("{GREEN}[{RED}JWP{PURPLE}.{BLUE}AFK{GREEN}] {BLUE}%N {DEFAULT}получает  1/2 предупреждений",i);
зачем там предупреждения

2017-08-06 12:36 UTC, mrkos9i4ok commented on addons/sourcemod/scripting/jwp_antiafk.sp
> +						JWP_ActionMsgAll("{GREEN}[{RED}JWP{PURPLE}.{BLUE}AFK{GREEN}] {BLUE}%N {DEFAULT}получает  1/2 предупреждений",i);
Да,лучше так писать))
Он мог случайно свернуть игру и другие дела делать,но в это время уже раунд новый начался.Вот ему даётся предупреждение перед переводом за Т команду.А если он и во втором раунде афк стоит,то его уже перекидывает за Т команду.

2017-08-06 12:40 UTC, TiBarification commented on addons/sourcemod/scripting/jwp_antiafk.sp
> +						JWP_ActionMsgAll("{GREEN}[{RED}JWP{PURPLE}.{BLUE}AFK{GREEN}] {BLUE}%N {DEFAULT}получает  1/2 предупреждений",i);
Сомневаюсь что эти предупреждения нужны. Даже если так, то не стоит их писать в чат всем игрокам. В вашем плагине всё захардкожено, обычный пользователь не сможет регулировать таймер афк отсчёта.

2017-08-06 12:43 UTC, mrkos9i4ok commented on addons/sourcemod/scripting/jwp_antiafk.sp
> +						JWP_ActionMsgAll("{GREEN}[{RED}JWP{PURPLE}.{BLUE}AFK{GREEN}] {BLUE}%N {DEFAULT}получает  1/2 предупреждений",i);
Можно через квары вытащить кол-во проверок(3 и 12) и уже там менять к примеру.
Кол-во секунд после начала раунда
Ax5
A = default 3
3x5 = 15 секунд

2017-08-06 12:54 UTC, mrkos9i4ok commented on addons/sourcemod/scripting/jwp_antiafk.sp
> +						JWP_ActionMsgAll("{GREEN}[{RED}JWP{PURPLE}.{BLUE}AFK{GREEN}] {BLUE}%N {DEFAULT}получает  1/2 предупреждений",i);
Сначала писалось только клиенту,что вы получили предупреждение,потом поменял так.

2017-08-15 14:38 UTC, TiBarification requested changes
Remove warnings from this module.
Also add multilang support.

2017-08-16 18:07 UTC, TiBarification approved these changes

2017-08-16 18:10 UTC, merged