Маленькие фиксы и руки срабатывают только после перезагрузки модуля
TiBarification/Jail-Warden-Pro pull request #69
Opened 2017-08-22 17:50 UTC by mrkos9i4ok

2017-08-22 17:50 UTC, mrkos9i4ok commented
Маленькое решение нашёл только вот такое
```
static const String: sExec[][] = 
{
	"sm plugins reload jwp_skin"
};

public OnMapStart()
{
	for(new i; i < sizeof(sExec); i++)
	{	
		ServerCommand(sExec[i]);
	}
}
```

2017-08-22 17:56 UTC, TiBarification requested changes

2017-08-22 17:56 UTC, TiBarification commented on addons/sourcemod/scripting/jwp_ratio.sp
> +void ChangeClientTeam(int client, int team)
А в чём собственно смысл этого действия?

2017-08-22 17:56 UTC, TiBarification commented on addons/sourcemod/scripting/jwp_skin.sp
> +				ArmsFix_RefreshView(client);
Зачем, когда это происходит в ф-ии SetActualModel.

2017-08-22 17:57 UTC, TiBarification commented
>Маленькое решение нашёл только вот такое
Стоит избегать таких решений, а подумать как сделать лучше.

2017-08-22 18:03 UTC, mrkos9i4ok commented on addons/sourcemod/scripting/jwp_skin.sp
> +				ArmsFix_RefreshView(client);
При спавне всем делает рефреш,а нужно только когда кмд с поста уходит,так вот сюда переместил

2017-08-22 18:10 UTC, mrkos9i4ok commented
> Стоит избегать таких решений, а подумать как сделать лучше.
Вот и создал,чтобы найти решения

2017-08-23 17:28 UTC, mrkos9i4ok commented
@TiBarification Так же ещё нашёл штуку:когда кмд погибает,то передается командирка заму,а вот скин у зама становится стандартного кт.
По моему такая система работает
1)Кмд погиб
2)Зам-->КМД
3)Снятие зама.И из-за этого становится стандартный скин.

2017-08-23 17:31 UTC, mrkos9i4ok commented
Нужно бы сначала зама снимать,а потом этому клиенту передавать командирку

2017-08-23 17:55 UTC, TiBarification approved these changes

2017-08-23 18:03 UTC, TiBarification commented
>Нужно бы сначала зама снимать,а потом этому клиенту передавать командирку

Ядро обновил.

2017-08-23 19:39 UTC, mrkos9i4ok commented
@TiBarification Я убрал n arms fix для себя,и руки выдаются без перезагрузки модуля

2017-08-24 20:20 UTC, mrkos9i4ok commented
@TiBarification xD Нашёл ещё решение,переименовал модуль в jwp_skins,теперь он догружается после того,как загрузится n arms fix.То есть теперь нормально руки.Проблема была в том,что N arms fix грузился после модуля,а перезагрузка модуля помогала снова в конец строя засунуть догрузку.

2017-08-24 21:17 UTC, mrkos9i4ok commented
Но вряд ли это всем поможет,уникальный трабл.У некоторых его может и не возникать

2017-08-24 21:17 UTC, TiBarification commented
Будем надеятся, когда-нибудь разработчики исправят или добавят нормальную последовательность загрузки плагинов. Пока что решением было переименовать файл.

2017-08-24 21:18 UTC, merged